ARG NODE_VERSION=18
ARG VERSION_OVERRIDE
ARG BRANCH_OVERRIDE
####################################################################################
FROM --platform=${BUILDPLATFORM} node:${NODE_VERSION} AS frontend-builder
ENV BUILD_NO_SERVER=true \
    BUILD_NO_HASH=true \
    BUILD_NO_CHUNKS=true \
    BUILD_MODULE=true \
    YARN_CACHE_FOLDER=/root/web/.yarn \
    NX_CACHE_DIRECTORY=/root/web/.nx \
    NODE_ENV=production

WORKDIR /label-studio/web

# Fix Docker Arm64 Build
RUN yarn config set registry https://registry.npmjs.org/
RUN yarn config set network-timeout 1200000 # HTTP timeout used when downloading packages, set to 20 minutes

COPY web/package.json .
COPY web/yarn.lock .
COPY web/tools tools
RUN --mount=type=cache,target=${YARN_CACHE_FOLDER},sharing=locked \
    --mount=type=cache,target=${NX_CACHE_DIRECTORY},sharing=locked \
    yarn install --prefer-offline --no-progress --pure-lockfile --frozen-lockfile --ignore-engines --non-interactive --production=false

COPY web .
COPY pyproject.toml ../pyproject.toml
RUN --mount=type=cache,target=${YARN_CACHE_FOLDER},sharing=locked \
    --mount=type=cache,target=${NX_CACHE_DIRECTORY},sharing=locked \
    yarn run build

################################ Stage: frontend-version-generator
FROM frontend-builder AS frontend-version-generator

ENV LS_DIR=/label-studio \
    HOME=/label-studio

RUN git config --global --add safe.directory /label-studio

RUN --mount=type=cache,target=${YARN_CACHE_FOLDER},sharing=locked \
    --mount=type=cache,target=${NX_CACHE_DIRECTORY},sharing=locked \
    --mount=type=bind,source=.git,target=../.git \
    yarn version:libs

# Directory setup and permissions
################################ Stage: frontend-version-generator
FROM alpine:3.21.2 AS production

ENV LS_DIR=/label-studio \
    HOME=/label-studio \
    LABEL_STUDIO_BASE_DATA_DIR=/label-studio/data \
    OPT_DIR=/opt/heartex/instance-data/etc

WORKDIR $LS_DIR

RUN set -eux; \
    apk update; \
    apk add --no-cache gnupg curl nginx bash; \
    apk del gnupg

RUN set -eux; \
    mkdir -p $LABEL_STUDIO_BASE_DATA_DIR $OPT_DIR \
    && chown -R 1001:0 $LABEL_STUDIO_BASE_DATA_DIR $OPT_DIR /etc/nginx /var/log/nginx

COPY --chown=1001:0 --from=frontend-builder                   $LS_DIR/web/dist                          $LS_DIR/web/dist
COPY --chown=1001:0 label_studio/core/static                  $LS_DIR/label_studio/core/static_build
COPY --chown=1001:0 --from=frontend-version-generator         $LS_DIR/web/dist/apps/labelstudio/version.json     $LS_DIR/web/dist/apps/labelstudio/version.json
COPY --chown=1001:0 --from=frontend-version-generator         $LS_DIR/web/dist/libs/editor/version.json         $LS_DIR/web/dist/libs/editor/version.json
COPY --chown=1001:0 --from=frontend-version-generator         $LS_DIR/web/dist/libs/datamanager/version.json    $LS_DIR/web/dist/libs/datamanager/version.json
COPY --chown=1001:0 deploy/default.conf /etc/nginx/nginx.conf
COPY --chown=1001:0 pyproject.toml .
COPY --chown=1001:0 README.md .
COPY --chown=1001:0 LICENSE LICENSE
COPY --chown=1001:0 licenses licenses
COPY --chown=1001:0 deploy deploy

USER 1001

EXPOSE 8000

ENTRYPOINT ["./deploy/docker-entrypoint.sh"]
CMD ["nginx"]
